# Generated by Django 4.2 on 2023-03-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataInTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coulumn_header_1', models.CharField(max_length=20)),
                ('coulumn_header_2', models.CharField(max_length=20)),
                ('coulumn_header_3', models.CharField(max_length=20)),
                ('coulumn_header_4', models.CharField(max_length=20)),
                ('coulumn1', models.CharField(max_length=20)),
                ('coulumn2', models.CharField(max_length=20)),
                ('coulumn3', models.CharField(max_length=20)),
                ('coulumn4', models.CharField(max_length=20)),
                ('table_that_data_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table')),
            ],
        ),
    ]
